version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "common/"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "core-service/"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "event-handler/"
    schedule:
      interval: "daily"
