CREATE TABLE IF NOT EXISTS events
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dtype        VARCHAR(255) NOT NULL,
    aggregate_id VARCHAR(36),
    type         VARCHAR(255) NOT NULL,
    timestamp    TIMESTAMP    NOT NULL DEFAULT current_timestamp,
    payload      JSONB
);