version: '3.0'

networks:
  banking:
    driver: bridge

volumes:
  db-data:
    driver: local

services:
  postgres:
    image: 'postgres:16.3-alpine'
    networks:
      - app
    env_file:
      - .env
    ports:
      - '5437:5432'
    volumes:
      - db-data:/var/lib/postgresql/data