package com.javade.events;

public enum EventType {

    CLIENT_CREATE,
    CLIENT_UPDATE,
    CLIENT_DELETE,
    CARD_CREATE,
    CARD_UPDATE,
    CARD_DELETE,
    TRANSACTION_CREATE,
    TRANSACTION_UPDATE,
    TRANSACTION_DELETE
}
